name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          pkg-config --libs --cflags alsa
          sudo apt-get install libgtk-3-dev
          cd creator
          cargo build --verbose --release

      - name: Move Resources
        run: |
          ls
          cd ..
          mkdir output
          mv target/release/creator output/eldiron-x86_64-unknown-linux-gnu
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/eldiron-x86_64-unknown-linux-gnu

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: output

  windows_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd creator
          cargo build --verbose --release

      - name: Move Resources
        run: |
          cd ..
          mkdir output
          mv target/release/creator.exe output/eldiron-x86_64-pc-windows-msvc.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/eldiron-x86_64-pc-windows-msvc.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: output

  linux_release:
    runs-on: ubuntu-latest
    needs: linux_build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Linux

      - name: Install Dependencies
        run: cargo install cargo-bundle

      - name: Build
        run: |
          mv eldiron-x86_64-unknown-linux-gnu creator/eldiron
          cd creator
          cargo bundle --release --bin eldiron
          cd ..
          mv target/release/bundle/deb/*.deb Eldiron.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Eldiron.deb

  windows_release:
    runs-on: windows-latest
    needs: windows_build
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Windows

      - name: Install WiX
        run: nuget install WiX -Version 3.11.2

      - name: Create MSI Installer
        run: |
          ./WiX.*/tools/heat.exe dir "output" -dr INSTALLDIR -ag -cg DynamicFragment \
            -ke -srd -sfrag -nologo -pog:Binaries -pog:Documents -pog: Satellites \
            -pog:Sources -pog:Content -out "./resources.wxs"
          ./WiX.*/tools/candle.exe -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./eldiron.wixobj" "./build/windows/wix/eldiron.wxs"
          ./WiX.*/tools/candle.exe -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./resources.wixobj" "./resources.wxs"
          ./WiX.*/tools/light.exe -ext WixUIExtension -ext WixUtilExtension \
            -out "./Eldiron.msi" -sice:ICE61 -sice:ICE91 "./eldiron.wixobj" "./resources.wixobj"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Eldiron.msi
